### ISSUE TITLE
Pre-release warning

### ISSUE THREAD

**Issue by cassidyjames** [elementary/onboarding#110]
## Problem

We keep getting issues and Slack messages about known issues in the daily builds. Plus, there are already some video walkthroughs popping up on the Internet.

## Proposal

Add a pre-release warning page to Onboarding. It can be added now and removed once we're ready for a stable release—or only shown when we know we're on an early build (i.e. if the codename is `next`, maybe?).

>:warning:
>**Pre-release Version**
>You're running an early daily build of elementary OS. Things will be broken.
>
>• Curated apps are not available in AppCenter
>• The visual style is unfinished
>• [More…](https://github.com/orgs/elementary/projects/55)

## Prior Art

Way back in the day we used to set a whole pre-release warning wallpaper. More recently we've set a purpleprint wallpaper, but that does less to communicate known issues.

**Comment by danrabbit** [comment]
This seems like a logical place to include pre-release warnings. I guess we just have to figure out what the mechanism is for displaying it and what the content should be

**Comment by meisenzahl** [comment]
I like the idea of only showing the warning when the codename is next.
