### ISSUE TITLE
EarlyAccessView added last instead of first

### ISSUE THREAD

**Issue by cassidyjames** [elementary/onboarding#123]
>Not sure if you want to fix it in a separate branch, but it looks like this is being packed last instead of first:
>
>![Screenshot from 2021-02-05 11 06 17@2x](https://user-images.githubusercontent.com/7277719/107077841-48e0ff80-67a2-11eb-86e3-8735c331d57a.png)
>
_Originally posted by @danrabbit in https://github.com/elementary/onboarding/issues/121#issuecomment-774229810_

**Comment by danrabbit** [comment]
Fixed in #124
