### ISSUE TITLE
Offer a link to inform people what Flatpak apps are during onboarding

### ISSUE THREAD

**Issue by orta** [elementary/onboarding#129]
## Problem

I think for folks who are not already deep into the Linux ecosystem this page can read like "You can use the AppCenter to get apps, _and_ you can side load Flatpak apps" - but it doesn't really have a way for me to know what a Flatpak app is. 

![Screen Shot 2021-04-30 at 9 53 49 AM](https://user-images.githubusercontent.com/49038/116672874-98e2f300-a99a-11eb-8fbe-b7af3fd71ba4.png)

## Proposal

Perhaps linking to https://blog.elementary.io/elementary-appcenter-flatpak/ or having a specific page on the site which gives context.

## Prior Art

N/A

**Comment by team-cons** [comment]
That complicate things needlessly IMHO. Whenever anything on a technical level gets brought up, i have flashback of that install party where a family mother brought her old laptop and some guy started telling her about arch and openbox

sideload is a bit of an expected function in an OS. I has app, i clicka da app, a dialog tells me about da app and installs it.

If someone wants to install a flatpak  they already know what a flatpak is.
If someone doesnt know, they probably wont look for random flatpakref files, or just double click one they found and get the sideload window.

**Comment by danirabbit** [comment]
Yeah I think I'm inclined to agree that this is basically solved for onboarding with the new design. We explain that there's a built in App Store and that apps can be side loaded from alternative App Stores. We mention Flatpak by name and link to a place to get more flatpak apps. I'm not sure there's more we can be doing here without making things unnecessarily complicated
