### ISSUE TITLE
Add additional accent color based on wallpaper

### ISSUE THREAD

**Issue by AceXare** [elementary/onboarding#133]
## Problem
The settings have a new feature: wallpaper based accent color, this should be also in the onboarding settings (only for consistency reasons).

## Proposal
Just add the same feature (the rainbow "button") as in settings -> appearance :)

**Comment by meisenzahl** [comment]
Was already added with https://github.com/elementary/onboarding/pull/126

**Comment by AceXare** [comment]
Oh Thanks, seems like I didn't search good enough..
