### ISSUE TITLE
Request to have the ability to turn off the welcome screen after seeing once

### ISSUE THREAD

**Issue by diddy-boy** [elementary/onboarding#134]
## Problem

The welcome screen is quite handy to have but after seeing this a few times, it would be nice to turn this off or remove it from the start up.
Each time I log in, the welcome screen is shown.
I have this on two installs so I assume this is a beta release behaviour

## Proposal

have an option to turn this off

**Comment by danrabbit** [comment]
It's intentional that this is shown every boot for early access. On a stable install it will only show once
