### ISSUE TITLE
Onboarding segfaults when user language is set to Polish

### ISSUE THREAD

**Issue by marmeladapk** [elementary/onboarding#141]
## What Happened

When onboarding tries to launch when user language is set to Polish is segfaults.

This is a problem since some time after onboarding was introduced in elementary OS 5. I saw onboarding once then after some updates I only saw logs of this crash. This problem persists on fresh install. I'm not sure if other languages are affected.

## Expected Behavior

Onboarding launches as for other languages.

## Steps to Reproduce

1. Create new user
2. Set its language to Polish
3. Login as this user. Onboarding will not show up and segfault will be recorder in system logs.
4. Changing lanugage to something else will fix this issue (I tried English, German, French)

### Logs

```
[306864.160243] io.elementary.o[3562054]: segfault at 1e ip 00007f030dbd5675 sp 00007ffcc832eac8 error 4 in libc-2.31.so[7f030da6f000+178000]
[306864.160253] Code: 00 00 0f 1f 00 31 c0 c5 f8 77 c3 66 2e 0f 1f 84 00 00 00 00 00 f3 0f 1e fa 89 f9 48 89 fa c5 f9 ef c0 83 e1 3f 83 f9 20 77 2b <c5> fd 74 0f c5 fd d7 c1 85 c0 0f 85 eb 00 00 00 48 83 c7 20 83 e1
```

## Platform Information

- elementary os 6.0, updated as of 06 sep
- onboarding: 6.0.0+r507+pkg10~ubuntu6.1

**Comment by jeremypw** [comment]
It seems I have sufficient rights and have changed `%s` to `%u` which hopefully will fix this.  Should be confirmed by a Polish speaker though.

**Comment by marmeladapk** [comment]
Fixed
