### ISSUE TITLE
Show option to schedule dark mode

### ISSUE THREAD

**Issue by danrabbit** [elementary/onboarding#142]
### Problem

When I set up a new computer, I'm offered the option to choose or dark or light mode, but I have to go into System Settings to choose scheduled dark mode which is what I really want

### Proposal

Include an option in Onboarding to choose sunset/sunrise scheduled dark mode

**Comment by ZenitsuDev** [comment]
Hi @danrabbit . I can work on it, but is it going to be in the look and feel view or is it going to have its own view?

**Comment by danrabbit** [comment]
@ZenitsuDev It should be on the same page as other look and feel options, but we can greatly simplify this from what's offered in System Settings. It could probably be as simple as a switch for choosing "sunset to sunrise". We don't need to handle manual scheduling here
