### ISSUE TITLE
Desktop file validation on autostart.desktop is failing.

### ISSUE THREAD

**Issue by amz-x** [elementary/onboarding#154]
### What Happened?

Issue with packaging the following application to Fedora due to invalid value on autostart.desktop entry:

```
NotShowIn=Installer;
```

### Steps to Reproduce

1. Execute following in root of project:

```
desktop-file-validate  ./data/autostart.desktop
```

2. Output:

```
./data/autostart.desktop: error: value "Installer;" for key "NotShowIn" in group "Desktop Entry" contains an unregistered value "Installer"; values extending the format should start with "X-"
```

### Expected Behavior

Desktop file validation should pass validation. I tested the changes on latest live ISO of elementary OS 6.1. 

### OS Version

Other Linux

### Software Version

Latest release (I have run all updates)

**Comment by decathorpe** [comment]
I wonder if it would be more generic and less "special" to use "OnlyShowIn=Pantheon;" instead?

"Pantheon" is a valid desktop environment identifier in desktop-file-utils, and this would also make the elementary onboarding app not show up when logging into GNOME, for example.

**Comment by amz-x** [comment]
> I wonder if it would be more generic and less "special" to use "OnlyShowIn=Pantheon;" instead?
> 
> "Pantheon" is a valid desktop environment identifier in desktop-file-utils, and this would also make the elementary onboarding app not show up when logging into GNOME, for example.

@decathorpe updated PR.
