### ISSUE TITLE
"Get Involved...": possibility of being customizable?

### ISSUE THREAD

**Issue by electricduck** [elementary/onboarding#174]
On the Welcome screen the **Get Involved...** link [is hardcoded](https://github.com/elementary/onboarding/blob/489480000904ecbee7c06fbcdab9f8a6beab927a/src/Views/WelcomeView.vala#L41-L45). This is slightly confusing when Pantheon is used on other distros, as the other links are set via various variables from `os-release`, and in order for Pantheon to be truely distro-agnostic this link should be customizable also.

Unfortunately, the `os-release` manpage offers no such variable that could be used for "getting involved" (there is `HOME_URL`, `DOCUMENTATION_URL`, `SUPPORT_URL`, `BUG_REPORT_URL`, and `PRIVACY_POLICY_URL`), so it'll either need to come from somewhere else or a non-standard variable in `os-release` will have to be used.

![image](https://user-images.githubusercontent.com/1594644/169125099-0f6876eb-0c7d-42e0-a206-bb7309686288.png)

**Comment by danrabbit** [comment]
I guess my line of thought here is that even if Pantheon is being used on a non-elementary distro you're still being encouraged to get involved with the development of Pantheon, so I'm not sure this link needs to change per distro

**Comment by electricduck** [comment]
Oh certaintly, I'm more thinking the Get Involved page is fairly elementaryOS-centric. Not that this is of concern yet at all, since I'm only aware of two distros that use Pantheon (including Sodalite) and both have a fairly small userbase who are very aware of the differences, but I imagine a fairly new user to a distro that uses Pantheon in the future that might not entirely be aware of elementaryOS might find the page slightly confusing, such as if they venture into the StackExchange for example. Just my two pence :smile:.
