### ISSUE TITLE
Improve tab key behaviour

### ISSUE THREAD

**Issue by CodingSpiderFox** [elementary/onboarding#217]
### Problem

When my mouse was not working, I still wanted to setup my fresh install of elementaryOS

Howevery, the tab key behaviour in the onboarding app seems kinda weird

### Proposal

When pressing the tab key, to iterate over the control elements in the app, it should be better visible what the active control with the focus currently is.

This is especially relevant for the dot-navigation where it is almost impossible for me to see which bubble is currently focused.

Also, it seems to me, that pressing the tab key does not only iterate over the "clickable" UI elements but also some other UI elements which can not actively be changed (e.g. labels, layout-related items like grids etc.)
These elements should be skipped when pressing the tab key so that I can iterate over the controls more quickly to make the changes I want to make.

**Comment by danirabbit** [comment]
It looks like you're right, non-visible carousel children are able to be tabbed to, which isn't desirable. Opened https://gitlab.gnome.org/GNOME/libadwaita/-/issues/724

Also opened #218 with a workaround

**Comment by CodingSpiderFox** [comment]
Thank you :)
