### ISSUE TITLE
Not clear if deleting temporary files is safe

### ISSUE THREAD

**Issue by jlnr** [elementary/onboarding#58]
Onboarding asks users whether they want to automatically delete temporary files every 30 days. 
If this is a safe operation, I think it should be turned on by default (similar to how old kernels are now automatically pruned). If it isn't safe, then why are new users offered the option? If anyone should know which non-user files can be deleted, then it is the operating system.

If we want to offer this option, then I think it should be specific enough that the target audience understands what's going on: "We can automatically empty the /tmp directory if you are sure none of your apps uses it for important data". But that's super deep into techie land :)

![1*Rncwyen7EHPQDWv4oWOkIA@2x](https://user-images.githubusercontent.com/70772/61950124-3d0d5e00-afad-11e9-92ff-3c9c338f1801.png)

This is not actually a new issue, the same wording is used in the switchboard plug.

![1*qWZHCeDnBkbDKvg7E0RZUw](https://user-images.githubusercontent.com/70772/61949812-51049000-afac-11e9-9ac8-335617d9c452.png)

**Comment by jlnr** [comment]
Side note, does deleting old files really protect my privacy in this case? Are they safely deleted (overwritten with ones and zeros etc.)? If yes, then that could also be useful information.

**Comment by cassidyjames** [comment]
I don't believe it's a "secure erase," but it does prevent other users on the machine from easily coming across your old or temporary files.

**Comment by dar5hak** [comment]
To communicate that it is safe, we could change the copy from **Temporary files** to **Unneeded temporary files** or **Obsolete temporary files**.

The equivalent text in the Switchboard plug could be **Automatically delete unneeded temporary files**.

And as @jlnr suggested, it might make sense to keep it on by default if we're really calling them unneeded.

I can work on this.

**Comment by cassidyjames** [comment]
As a note, we're planning to enable this by default on elementary OS 6. I'd be happy rewording to include "unneeded" or something similar.

**Comment by dar5hak** [comment]
I did look up the thesaurus while suggesting "unneeded" and there's really nothing simpler and better. 😄
