### ISSUE TITLE
Icon does not fallback if distro doesn't provide it in os-release

### ISSUE THREAD

**Issue by cassidyjames** [elementary/onboarding#65]
Caused by https://github.com/elementary/onboarding/pull/64. Reproducible in Pop!_OS (and probably Ubuntu?).

**Comment by worldofpeace** [comment]
> Re: https://github.com/elementary/onboarding/pull/64#issuecomment-533293146
@cassidyjames What does the os-release file look like exactly?

**Comment by cassidyjames** [comment]
```ini
NAME="Pop!_OS"
VERSION="19.04"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Pop!_OS 19.04"
VERSION_ID="19.04"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=disco
UBUNTU_CODENAME=disco
```

**Comment by worldofpeace** [comment]
With that file, switchboard-plug-about also lacks a logo.

**Comment by worldofpeace** [comment]
I can reproduce this with other values in both switchboard-plug-about and onboarding, so I don't think https://github.com/elementary/onboarding/pull/64 is the cause.

**Comment by danrabbit** [comment]
This seems like a third case where both `distributor-logo` is not provided and no alternative is provided by os-release. Not sure what we can do there

**Comment by cassidyjames** [comment]
It works in Pop!_OS before 03975bacb75741d3dd391a126217e415f43c6059. `distributor-logo` is provided. For some reason it's not being loaded on Pop!_OS after 03975bacb75741d3dd391a126217e415f43c6059. Not the biggest deal, but we should probably fix the fallback code if we're going to pretend it correctly falls back.

**Comment by cassidyjames** [comment]
![Screenshot from 2019-09-19 16-51-32](https://user-images.githubusercontent.com/611168/65286833-35c28680-dafe-11e9-8887-235e59402541.png)

## Before 03975bacb75741d3dd391a126217e415f43c6059

![Screenshot from 2019-09-19 16-52-08](https://user-images.githubusercontent.com/611168/65286822-2f340f00-dafe-11e9-8eec-0f3fb9b6be05.png)

## After 03975bacb75741d3dd391a126217e415f43c6059

![Screenshot from 2019-09-19 16-54-21](https://user-images.githubusercontent.com/611168/65286818-293e2e00-dafe-11e9-82f6-b83b84de4fdd.png)

**Comment by cassidyjames** [comment]
If I inspect it and explicitly set the image's icon-name to `distributor-logo` it works, so it looks like the name is not correctly getting set.

**Comment by worldofpeace** [comment]
With added debug messaging the value is clearly `null`.

**Comment by danrabbit** [comment]
That's interesting, I wonder why that would return null

**Comment by cassidyjames** [comment]
Ah, this isn't erroring, meaning the catch isn't executing. We don't explicitly do any null checks.

https://github.com/elementary/onboarding/blob/9f61b81cb619396e3bff91e6e688a71b3b8616df/src/Utils.vala#L58-L77
