### ISSUE TITLE
Use os-distributor icon

### ISSUE THREAD

**Issue by cassidyjames** [elementary/onboarding#74]
It seems weird that this uses the installer icon, which metaphorically implies the OS still needs to be installed to disk (with its down arrow). Instead we should probably just use the os-distributor icon for the app. Alternatively we could come up with something new, but I think os-distributor makes perfect sense.

**Comment by meisenzahl** [comment]
Can this issue be closed? I think it was fixed with

- https://github.com/elementary/onboarding/pull/82
- https://github.com/elementary/onboarding/pull/93

**Comment by danrabbit** [comment]
Yes this should be fixed now
