### ISSUE TITLE
Onboarding is displayed as "Welcome"

### ISSUE THREAD

**Issue by 4jNsY6fCVqZv** [elementary/onboarding#81]
![Screenshot](https://user-images.githubusercontent.com/46536067/70635410-c3100580-1c2b-11ea-8cb8-185e526fd162.png)

Is that intentional?

**Comment by cassidyjames** [comment]
Yes, it comes from the AppData. The thinking was that “Onboarding” is not a super friendly user-facing term. 

https://github.com/elementary/onboarding/blob/3e40f6bad8686bbbf152995143f27e1de2d15926/data/onboarding.appdata.xml.in#L7

**Comment by 4jNsY6fCVqZv** [comment]
Thanks for your feedback! Would you say that "Welcome" explains well to the user of a freshly installed operating system what to expect in this app?
Wasn't the idea that the onboarding app should gradually explain new features to users?
"Welcome" is usually only said at the beginning. Admittedly, even an onboarding process is usually nothing continuous. But in terms of introducing new features, I see "onboarding" as a stronger metaphor to describe it.
Of course I can also say "Welcome" to every new feature. That's what you meant, isn't it?
You see, I don't find the wording itself very easy at this point. That's why I asked.
