### ISSUE TITLE
Add an elementary account Oauth view

### ISSUE THREAD

**Issue by cassidyjames** [elementary/onboarding#87]
We want to prompt for payment details in Onboarding, but need to make sure it's clear:

- Why we're asking (used for payments in AppCenter)
- How to manage it later
- That it's stored securely
- That we'll always prompt for payments

**Comment by cassidyjames** [comment]
As discussed, this will actually likely be a hybrid payment details/account page. @danrabbit mentioned that the authenticator should probably support locally storing payment details to not require an account, which means the copy here should reflect that. We'll want to encourage an account as a primary flow since users will get saved payment details across devices, synced purchase history, etc. that way.

**Comment by danrabbit** [comment]
Updating this to reflect the latest discussion:

When users go to purchase an app, they'll be prompted to add their payment info at that time, so there's no real value to having them do that head of time. So it's not really the wallet that we want to promote here.

What we really want is for users to sign up/in for restoring purchases. But if we link them to online accounts, that's pretty open ended and it's a lot of UI to throw that may not result in the user making it to adding an elementary account.

Therefore, it seems like the best thing to do is to embed the OAuth/Online Accounts flow in the dialog.

**Comment by danirabbit** [comment]
I'm going to close this since we don't currently actually have this service and I'm certain we'll remember to add it to onboarding if we did have such a thing
