### ISSUE TITLE
Mention Flatpak

### ISSUE THREAD

**Issue by danrabbit** [elementary/onboarding#99]
We've gotten some pretty consistent feedback that users still feel the way to sideload apps is by using Deb packages, which of course we don't support.

On the apps page, we should probably mention sideloading Flatpak apps in addition to getting apps from AppCenter

**Comment by cassidyjames** [comment]
On the one hand, I feel like users shouldn't care about the underlying technology… but on the other hand, it might help guide more technical users in the right direction. :thinking: We can try it.
